### PR TITLE
ROKOMobi wrapper implementation.

### PR DESCRIPTION
**Pull request by Zaakk**

### CODE REVIEW

**Comment by Zaakk** [comment]
these errors are caused by the ROKOMobi SDK constant (123) not being included in MPEnums.h of the main mParticle SDK. What we have to do to fix the issue?

**Comment by samdozor** [comment]
Hi @Zaakk - would you mind resubmitting your PR, but to the repo below? Thanks!

https://github.com/mparticle-integrations/mparticle-apple-integration-rokomobi

**Comment by jngnyc** [comment]
Hi @samdozor - Jimmy here, technical PM for this integration. https://github.com/mparticle-integrations/mparticle-apple-integration-rokomobi is returning a 404 for the both of us. 

**Can you assist?**

**Comment by samdozor** [comment]
Hi Jimmy, please try again, should be resolved.

**Pull request closed without merging**
